#!/bin/bash

clear
cp client_PFS scott
cd scott

# Get IP address
ip=`hostname -i`

# ./client_PFS <server_ip> <server_port>
my_name=Scott
server_ip=$ip
server_port=5555

echo ./client_PFS $my_name $server_ip $server_port
./client_PFS $my_name $server_ip $server_port

rm client_PFS
cd ..