#!/bin/bash

# ./GBNserver <server_port> <error_rate> <random_seed> <output_file> <recieve_log>
server_port=5555
error_rate=0
random_seed=0
output_file=sout.txt
recieve_log=slog.txt

echo ./GBNserver $server_port $error_rate $random_seed $output_file $recieve_log
./GBNserver $server_port $error_rate $random_seed $output_file $recieve_log