#!/bin/bash

# Quick Test Script
echo "<========= File Comparision =========>"
diff=`diff foo1 sout.txt | wc -c`

if [ $diff > 0 ]; then
	echo "Diff Failure"
else
	echo "Diff Success"
fi

wc foo1 sout.txt

echo "<====== Log Comparision - HEAD ======>"
head *log.txt

echo "<====== Log Comparision - TAIL ======>"
tail *log.txt