#!/bin/bash
# Quick Test Script

#Nodes="A
#B
#C
#D
#E
#F"
#node=($Nodes)
node=( {A..F} )

for i in 0 1 2 3 4 5
do
	echo "./routed_LS ${node[$i]} ${node[$i]}.log init.txt"
	./routed_LS ${node[i]} ${node[i]}.log init.txt &
done
